import type { StorefrontThemeConfig } from "@/types/services/storefront";

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  config: StorefrontThemeConfig;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: "aurora-bloom",
    name: "Aurora Bloom",
    description: "Fresh blues with crisp whites for a gallery aesthetic.",
    config: {
      primaryColor: "#2563eb",
      palette: {
        background: "#f4f7fb",
        surface: "#ffffff",
        surfaceMuted: "#e2e8f0",
        accent: "#2563eb",
        accentSoft: "#cfe0ff",
        text: "#0f172a",
        textMuted: "#475569",
        border: "#d7e0ee",
      },
    },
  },
  {
    id: "terra-cotta",
    name: "Terra Cotta",
    description: "Earthy clay tones for artisan storefronts.",
    config: {
      primaryColor: "#b45309",
      palette: {
        background: "#fdf4ed",
        surface: "#fff7f1",
        surfaceMuted: "#fde2cf",
        accent: "#b45309",
        accentSoft: "#f9cf9f",
        text: "#432819",
        textMuted: "#7c5a46",
        border: "#f0d3bb",
      },
    },
  },
  {
    id: "noir-luxe",
    name: "Noir Luxe",
    description: "Deep charcoal with gold highlights.",
    config: {
      primaryColor: "#facc15",
      palette: {
        background: "#0b0f19",
        surface: "#111827",
        surfaceMuted: "#1f2937",
        accent: "#facc15",
        accentSoft: "#fde68a",
        text: "#f8fafc",
        textMuted: "#cbd5f5",
        border: "#2b3447",
      },
    },
  },
  {
    id: "sage-harvest",
    name: "Sage Harvest",
    description: "Organic greens with soft linen neutrals.",
    config: {
      primaryColor: "#15803d",
      palette: {
        background: "#f5f7f2",
        surface: "#ffffff",
        surfaceMuted: "#e8f0e3",
        accent: "#15803d",
        accentSoft: "#b7e4c7",
        text: "#0b4616",
        textMuted: "#4c6f52",
        border: "#d5e6cf",
      },
    },
  },
  {
    id: "midnight-plum",
    name: "Midnight Plum",
    description: "Moody violets with rosy highlights.",
    config: {
      primaryColor: "#9d174d",
      palette: {
        background: "#0f0a1a",
        surface: "#1f1430",
        surfaceMuted: "#2f1f42",
        accent: "#9d174d",
        accentSoft: "#f5c2d1",
        text: "#fdf2f8",
        textMuted: "#e0b2c4",
        border: "#382447",
      },
    },
  },
  {
    id: "citrus-pop",
    name: "Citrus Pop",
    description: "Energetic oranges balanced with slate grays.",
    config: {
      primaryColor: "#f97316",
      palette: {
        background: "#fef6ec",
        surface: "#ffffff",
        surfaceMuted: "#ffe7d1",
        accent: "#f97316",
        accentSoft: "#ffd7ba",
        text: "#1f2933",
        textMuted: "#6b7280",
        border: "#fde1c6",
      },
    },
  },
  {
    id: "desert-sun",
    name: "Desert Sun",
    description: "Sun-bleached sands with copper highlights.",
    config: {
      primaryColor: "#d97706",
      palette: {
        background: "#f9f4ed",
        surface: "#fffaf5",
        surfaceMuted: "#f1e3d2",
        accent: "#d97706",
        accentSoft: "#f1c27d",
        text: "#4a3728",
        textMuted: "#8b6f52",
        border: "#e5d2bf",
      },
    },
  },
  {
    id: "coastal-fog",
    name: "Coastal Fog",
    description: "Sea-glass tones and misty grays for calm retail.",
    config: {
      primaryColor: "#0f766e",
      palette: {
        background: "#f2fbfb",
        surface: "#ffffff",
        surfaceMuted: "#e0f2f1",
        accent: "#0f766e",
        accentSoft: "#c7f4f0",
        text: "#0a2f34",
        textMuted: "#497981",
        border: "#d1e7e8",
      },
    },
  },
  {
    id: "sunset-sorbet",
    name: "Sunset Sorbet",
    description: "Gradient-ready peaches with berry text.",
    config: {
      primaryColor: "#ec4899",
      palette: {
        background: "#fff5f7",
        surface: "#fff0f5",
        surfaceMuted: "#ffe4ed",
        accent: "#ec4899",
        accentSoft: "#fbcfe8",
        text: "#831843",
        textMuted: "#be185d",
        border: "#f9d7e6",
      },
    },
  },
  {
    id: "forest-muse",
    name: "Forest Muse",
    description: "Deep greens paired with cream highlight.",
    config: {
      primaryColor: "#14532d",
      palette: {
        background: "#f7fbf8",
        surface: "#ffffff",
        surfaceMuted: "#e8f5e9",
        accent: "#14532d",
        accentSoft: "#bbf7d0",
        text: "#102316",
        textMuted: "#4d6b56",
        border: "#d4e8d5",
      },
    },
  },
  {
    id: "carbon-rose",
    name: "Carbon Rose",
    description: "Bold contrast of charcoal and rose gold.",
    config: {
      primaryColor: "#f472b6",
      palette: {
        background: "#090b12",
        surface: "#141823",
        surfaceMuted: "#1e2432",
        accent: "#f472b6",
        accentSoft: "#fbcfe8",
        text: "#f8fafc",
        textMuted: "#c7cad8",
        border: "#2a3145",
      },
    },
  },
  {
    id: "amber-koi",
    name: "Amber Koi",
    description: "Lush copper and teal for boutique jewelry brands.",
    config: {
      primaryColor: "#b45309",
      palette: {
        background: "#f6f3f0",
        surface: "#fffdf9",
        surfaceMuted: "#efe6de",
        accent: "#b45309",
        accentSoft: "#f3c196",
        text: "#2c1b11",
        textMuted: "#7c5f4a",
        border: "#ead8c7",
      },
    },
  },
  {
    id: "arctic-light",
    name: "Arctic Light",
    description: "Minimal frosty whites with cobalt accent.",
    config: {
      primaryColor: "#1d4ed8",
      palette: {
        background: "#f5f9ff",
        surface: "#ffffff",
        surfaceMuted: "#e7efff",
        accent: "#1d4ed8",
        accentSoft: "#bfdbfe",
        text: "#111827",
        textMuted: "#374151",
        border: "#d8e3fc",
      },
    },
  },
  {
    id: "velvet-night",
    name: "Velvet Night",
    description: "Luxe plum and brass for premium drops.",
    config: {
      primaryColor: "#c084fc",
      palette: {
        background: "#140e1f",
        surface: "#1f152f",
        surfaceMuted: "#2b1d43",
        accent: "#c084fc",
        accentSoft: "#e9d5ff",
        text: "#fdf4ff",
        textMuted: "#d8b4fe",
        border: "#382250",
      },
    },
  },
  {
    id: "cafe-au-lait",
    name: "Café au Lait",
    description: "Warm latte hues for lifestyle brands.",
    config: {
      primaryColor: "#a16207",
      palette: {
        background: "#fbf7f2",
        surface: "#fffbf5",
        surfaceMuted: "#f1e5d8",
        accent: "#a16207",
        accentSoft: "#f5cf9d",
        text: "#3c2a1c",
        textMuted: "#7b5c46",
        border: "#eadac8",
      },
    },
  },
  {
    id: "lime-fizz",
    name: "Lime Fizz",
    description: "Playful lime and midnight slate.",
    config: {
      primaryColor: "#65a30d",
      palette: {
        background: "#f6ffed",
        surface: "#ffffff",
        surfaceMuted: "#e4f7d1",
        accent: "#65a30d",
        accentSoft: "#d9f99d",
        text: "#1f2937",
        textMuted: "#4b5563",
        border: "#dfeecc",
      },
    },
  },
  {
    id: "bold-meridian",
    name: "Bold Meridian",
    description: "Modern cyan + charcoal blend for tech retail.",
    config: {
      primaryColor: "#0ea5e9",
      palette: {
        background: "#030712",
        surface: "#0f172a",
        surfaceMuted: "#1e293b",
        accent: "#0ea5e9",
        accentSoft: "#bae6fd",
        text: "#e2e8f0",
        textMuted: "#94a3b8",
        border: "#24324b",
      },
    },
  },
  {
    id: "petal-prism",
    name: "Petal Prism",
    description: "Soft lavender & mint for beauty drops.",
    config: {
      primaryColor: "#a855f7",
      palette: {
        background: "#fbf5ff",
        surface: "#ffffff",
        surfaceMuted: "#f3e8ff",
        accent: "#a855f7",
        accentSoft: "#e9d5ff",
        text: "#3b0764",
        textMuted: "#7c3aed",
        border: "#efd6ff",
      },
    },
  },
  {
    id: "retro-pop",
    name: "Retro Pop",
    description: "High-contrast amber and teal for bold shops.",
    config: {
      primaryColor: "#fbbf24",
      palette: {
        background: "#fffdf5",
        surface: "#ffffff",
        surfaceMuted: "#fff1cc",
        accent: "#f97316",
        accentSoft: "#ffd89a",
        text: "#0f172a",
        textMuted: "#5c6b82",
        border: "#ffe4b5",
      },
    },
  },
  {
    id: "slate-rose",
    name: "Slate Rose",
    description: "Balanced slate neutrals with rose blush.",
    config: {
      primaryColor: "#be123c",
      palette: {
        background: "#f9fafb",
        surface: "#ffffff",
        surfaceMuted: "#f3f4f6",
        accent: "#be123c",
        accentSoft: "#fecdd3",
        text: "#111827",
        textMuted: "#6b7280",
        border: "#e5e7eb",
      },
    },
  },
  {
    id: "steelwave",
    name: "Steelwave",
    description: "Industrial blues matched with silver edges.",
    config: {
      primaryColor: "#0f172a",
      palette: {
        background: "#f3f6fb",
        surface: "#ffffff",
        surfaceMuted: "#e1e8f5",
        accent: "#2563eb",
        accentSoft: "#bfdbfe",
        text: "#111827",
        textMuted: "#4b5563",
        border: "#d7e1f1",
      },
    },
  },
  {
    id: "mojave-neon",
    name: "Mojave Neon",
    description: "Desert dusk neutrals + electric magenta.",
    config: {
      primaryColor: "#db2777",
      palette: {
        background: "#fdf8f3",
        surface: "#fffaf5",
        surfaceMuted: "#f5ded0",
        accent: "#db2777",
        accentSoft: "#f9a8d4",
        text: "#3b161f",
        textMuted: "#7b2c40",
        border: "#f1ccc0",
      },
    },
  },
  {
    id: "neon-mint",
    name: "Neon Mint",
    description: "Vibrant mint balanced with graphite.",
    config: {
      primaryColor: "#10b981",
      palette: {
        background: "#f2fffb",
        surface: "#ffffff",
        surfaceMuted: "#dff7ee",
        accent: "#10b981",
        accentSoft: "#a7f3d0",
        text: "#02363a",
        textMuted: "#3f7067",
        border: "#d2eadf",
      },
    },
  },
  {
    id: "inkwell",
    name: "Inkwell",
    description: "Sleek monochrome ideal for editorial products.",
    config: {
      primaryColor: "#111827",
      palette: {
        background: "#f9fafb",
        surface: "#ffffff",
        surfaceMuted: "#eef1f5",
        accent: "#111827",
        accentSoft: "#9ca3af",
        text: "#0f172a",
        textMuted: "#6b7280",
        border: "#e5e7eb",
      },
    },
  },
];

